name: my_id
description: "A new Flutter project."


publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  myid: ^1.3.9
  dio: ^5.9.0
  equatable: ^2.0.7
  bloc: ^9.0.0
  flutter_bloc: ^9.1.1
  pretty_dio_logger: ^1.4.0
  envied: ^1.2.1
  dartz: ^0.10.1
  get_it: ^8.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  envied_generator: ^1.2.1
  mockito: ^5.5.0
  build_runner: ^2.4.8

flutter:

  uses-material-design: true






























